### ISSUE TITLE
Failed Android 9 decrypt

### ISSUE THREAD

**Issue by ghost** [CaptainThrowback/android_device_htc_m8#3]
twrp-3.3.1-0_CPTB-20191021-01-m8.img
LineageOS 16

Pattern lock.

Whether the correct or wrong pattern is entered the outcome and time it takes is the same:

Unable to mount storage
Running boot script...
Done.
E:Decrypt took too long, killing process
Failed to decrypt data.

And back to the pattern screen with "Pattern failed, please try again!"

**Comment by CaptainThrowback** [comment]
Where are the logs?

**Comment by ghost** [comment]
Attempt to save the log produces no obvious results. Says it saves to /data/media/ but all that's in /data/ is otp.txt

**Comment by CaptainThrowback** [comment]
Pull the log with adb.

`adb pull /tmp/recovery.log`

**Comment by ghost** [comment]
> Running boot script...
> I:VendorInit:Updating device properties based on MID and CID...
> I:VendorInit:MID Found: 0P6B16000
> I:VendorInit:CID Found: TELUS001
> I:VendorInit:Current product: m8
> I:VendorInit:New product: htc_m8
> I:VendorInit:Current device: m8
> I:VendorInit:New device: htc_m8
> I:VendorInit:Current model: HTC One_M8
> I:/sbin/runatboot.sh process ended with RC=0
> Done.
> I:Is encrypted, do decrypt page first
> I:Switching packages (TWRP)
> I:Set page: 'decrypt'
> I:Set page: 'decrypt_pattern'
> I:Set page: 'trydecrypt'
> I:operation_start: 'Decrypt'
> I:PrepDecrypt:Running prepdecrypt script for TWRP...
> I:PrepDecrypt:Looking for /vendor/bin/qseecomd to update linker path...
> I:PrepDecrypt:File found! Relinking /vendor/bin/qseecomd to /sbin/qseecomd...
> I:PrepDecrypt:Looking for /vendor/bin/hw/android.hardware.keymaster@3.0-service to update linker path...
> I:PrepDecrypt:File not found. Proceeding without relinking...
> I:PrepDecrypt:Temporary system folder created at /s.
> I:PrepDecrypt:system mounted at /s.
> I:PrepDecrypt:Build.prop exists! Reading system properties from build.prop...
> I:PrepDecrypt:Current system Android SDK version: 28
> I:PrepDecrypt:No Original OS Version found. Proceeding with existing value.
> I:PrepDecrypt:Current OS version: 8.1.0
> I:PrepDecrypt:No Original security patch level found. Proceeding with existing value.
> I:PrepDecrypt:Current security patch level: 2018-11-05
> I:PrepDecrypt:Current fingerprint: htc/omni_m8/m8:8.1.0/OPM8.181105.002/throwb10211314:eng/test-keys
> I:PrepDecrypt:New fingerprint: htc/lineage_m8/m8:9/PQ3A.190801.002/c5eba4df94:userdebug/release-keys
> I:PrepDecrypt:crypto.ready=1
> I:PrepDecrypt:Script complete. Device ready for decryption.
> D:crypt_ftr->fs_size = 53215232
> I:Using scrypt with keymaster for cryptfs KDF
> I:TWRP keymaster max API: 3
> I:Signing safely-padded objectkeymaster module name is Keymaster QCOM HAL
> keymaster version is 3
> Found keymaster0 module, using keymaster0 API.
> could not open keymaster device in keystore (Operation not permitted)
> Failed to init keymaster 0/1
> E:Decrypt took too long, killing process
> I:Child process killed successfully
> Failed to decrypt data.
> I:Set page: 'decrypt'
> I:Set page: 'decrypt_pattern'
> I:operation_end - status=1
> I:Set page: 'cancel_decrypt'
> I:Set page: 'main'
> I:Set page: 'clear_vars'
> I:Set page: 'main2'
> I:Set page: 'main'
> I:Set page: 'clear_vars'
> I:Set page: 'main2'
> SELinux contexts loaded from /file_contexts
> Full SELinux support is present.
> I:Unable to mount settings storage during GUI startup.
> I:TWFunc::Fixup_Time: Pre-fix date and time: 2019-10-21--20-36-26
> I:TWFunc::Fixup_Time: Setting time offset from file /sys/class/rtc/rtc0/since_epoch
> I:TWFunc::Fixup_Time: Date and time corrected: 2019-10-21--20-36-26
> I:Unable to find source file /cache/recovery/log.gz
> Unable to mount /data/media/TWRP/.twrps
> I:Attempt to load settings from settings file...
> I:InfoManager file '/data/media/TWRP/.twrps' not found.
> I:Backup folder set to '/data/media/TWRP/BACKUPS/SH44XWM04645'
> I:Mount: Unable to find partition for path '/etc'
> I:Copied file /etc/recovery.fstab to /cache/recovery/recovery.fstab
> I:Version number saved to '/cache/recovery/.version'
> I:Unable to mount '/usb_otg'
> I:Actual block device: '', current file system: 'vfat'
> I:TWFunc::Set_Brightness: Setting brightness control to 255
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/en.xml' directly
> parsing languageFile
> parsing languageFile done
> I:Translating partition display names
> I:Backup folder set to '/data/media/TWRP/BACKUPS/SH44XWM04645'
> I:Switching packages (TWRP)
> I:Set page: 'system_readonly'
> I:Is_Mounted: Unable to find partition for path '/vendor'
> I:operation_start: 'Toggle System Mount'
> I:operation_end - status=1
> I:Set page: 'main'
> I:Set page: 'clear_vars'
> I:Set page: 'main2'
> I:Set page: 'main'
> I:Set page: 'clear_vars'
> I:Set page: 'main2'
> I:Switching packages (TWRP)
> I:Starting Adb Backup FIFO
> I:Set page: 'main'
> I:Set page: 'clear_vars'
> I:Set page: 'main2'
> I:Set page: 'advanced'
> I:Set page: 'copylog'
> I:Set page: 'action_page'
> I:operation_start: 'Copy Log'
> I:Copied file /tmp/recovery.log to /data/media/recovery.log
> I:Cannot find file /data/media/dmesg.log
> Copied kernel log to /data/media/dmesg.log
> Copied recovery log to /data/media/recovery.log.
> I:Set page: 'action_complete'
> I:operation_end - status=0
> I:Set page: 'clear_vars'
> I:Set page: 'advanced'
> I:Set page: 'terminalcommand'
> I:Set page: 'advanced'
> I:Set page: 'filemanagerlist'
> I:Set page: 'filemanageroptions'
> I:Set page: 'filemanagerlist'
> I:Set page: 'advanced'
> I:Set page: 'filemanagerlist'
> I:Set page: 'advanced'
> I:Set page: 'copylog'
> I:Set page: 'action_page'
> I:operation_start: 'Copy Log'
> I:Copied file /tmp/recovery.log to /data/media/recovery.log
> I:Cannot find file /data/media/dmesg.log
> Copied kernel log to /data/media/dmesg.log
> Copied recovery log to /data/media/recovery.log.
> I:Set page: 'action_complete'
> I:operation_end - status=0
> I:Set page: 'clear_vars'
> I:Set page: 'advanced'
> I:Set page: 'filemanagerlist'
> I:Set page: 'advanced'
> I:Set page: 'copylog'
> I:Set page: 'action_page'
> I:operation_start: 'Copy Log'
> I:Copied file /tmp/recovery.log to /data/media/recovery.log
> I:Cannot find file /data/media/dmesg.log
> Copied kernel log to /data/media/dmesg.log
> Copied recovery log to /data/media/recovery.log.
> I:Set page: 'action_complete'
> I:operation_end - status=0
> I:Set page: 'clear_vars'
> I:Set page: 'advanced'
> I:Set page: 'main'
> I:Set page: 'clear_vars'
> I:Set page: 'main2'
> I:Set page: 'settings'
> I:Set page: 'main'
> I:Set page: 'clear_vars'
> I:Set page: 'main2'
> I:Set page: 'advanced'
> I:Set page: 'filemanagerlist'
> I:Set page: 'filemanageroptions'
> I:Set page: 'filemanageroptions'
> I:Set page: 'filemanagerlist'
> I:Set page: 'advanced'
> I:Set page: 'filemanagerlist'
> Truncating string cache entries.
> I:TWFunc::Set_Brightness: Setting brightness control to 5
> I:TWFunc::Set_Brightness: Setting brightness control to 255
> I:Set page: 'filemanageroptions'
> I:Set page: 'filemanagerlist'
> I:Set page: 'main'
> I:Set page: 'clear_vars'
> I:Set page: 'main2'

**Comment by CaptainThrowback** [comment]
Thank you. Building a new version and will post here for you to test.

**Comment by CaptainThrowback** [comment]
Please try the below version (unzip first) and let me know if decryption works. Thanks!

[twrp-3.3.1-0_CPTB-20191021-02-m8.img.zip](https://github.com/CaptainThrowback/android_device_htc_m8/files/3752907/twrp-3.3.1-0_CPTB-20191021-02-m8.img.zip)

**Comment by ghost** [comment]
Same problem persists. First attempt correct pattern, second attempt deliberately wrong pattern, third attempt correct pattern. All took the exact same time to fail.


> Starting TWRP 3.3.1-0_CPTB-20191021-02-d0124ff0 on Mon Oct 21 21:14:05 2019
>  (pid 229)
> I:Lun file '/sys/class/android_usb/android0/f_mass_storage/lun0/file'
> TW_INCLUDE_CRYPTO := true
> I:Found brightness file at '/sys/class/leds/lcd-backlight/brightness'
> I:Got max brightness 255 from '/sys/class/leds/lcd-backlight/max_brightness'
> I:TWFunc::Set_Brightness: Setting brightness control to 255
> I:LANG: en
> Starting the UI...
> setting DRM_FORMAT_RGB565 and GGL_PIXEL_FORMAT_RGB_565
> cannot find/open a drm device: No such file or directory
> fb0 reports (possibly inaccurate):
>   vi.bits_per_pixel = 32
>   vi.red.offset   =  24   .length =   8
>   vi.green.offset =  16   .length =   8
>   vi.blue.offset  =   8   .length =   8
> setting GGL_PIXEL_FORMAT_RGBX_8888
> double buffered
> framebuffer: 0 (1080 x 1920)
> Using fbdev graphics.
> I:TWFunc::Set_Brightness: Setting brightness control to 255
> I:Loading package: splash (/twres/splash.xml)
> I:Load XML directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/splash.xml' directly
> I:Checking resolution...
> I:Loading resources...
> I:Loading variables...
> I:Loading mouse cursor...
> I:Loading pages...
> I:Loading page splash
> I:Switching packages (splash)
> I:minui: /sys/board_properties/virtualkeys.synaptics-rmi-touchscreen is 5 % 6
> => Linking mtab
> => Processing /etc/recovery.fstab
> I:Reading /etc/recovery.fstab
> I:Processing '/boot'
> I:Processing '/cache'
> I:Processing '/system'
> I:Processing '/data'
> I:Processing '/misc'
> I:Processing '/recovery'
> I:Processing '/devlog'
> I:Created '/devlog' folder.
> I:Processing '/carrier'
> I:Created '/carrier' folder.
> I:Processing '/reserve'
> I:Created '/reserve' folder.
> I:Processing '/external_sd'
> I:Created '/external_sd' folder.
> I:Processing '/usb_otg'
> I:Created '/usb_otg' folder.
> I:Processing '/sd_ext'
> I:Created '/sd_ext' folder.
> I:Done processing fstab files
> I:Can't probe device /dev/block/mmcblk0p47
> I:Unable to mount '/data'
> I:Actual block device: '/dev/block/mmcblk0p47', current file system: ''
> I:Using automatic handling for /data/media emulated storage device.
> I:Setting up '/data' as data/media emulated storage.
> I:Created '/and-sec' folder.
> I:Creating Android Secure: /external_sd/.android_secure
> I:mount -o bind '/external_sd/.android_secure' '/and-sec' process ended with RC=0
> I:Backup folder set to '/data/media/TWRP/BACKUPS/SH44XWM04645'
> I:Settings storage is '/data/media'
> Updating partition details...
> I:Unable to mount '/usb_otg'
> I:Actual block device: '', current file system: 'vfat'
> I:Can't probe device /dev/block/mmcblk1
> I:Unable to mount '/sd_ext'
> I:Actual block device: '/dev/block/mmcblk1', current file system: ''
> ...done
> Unable to mount storage
> I:Unmounting main partitions...
> 
> 
> Partition Logs:
> /boot | /dev/block/mmcblk0p42 | Size: 16MB
>    Flags: Can_Be_Backed_Up IsPresent Can_Flash_Img 
>    Primary_Block_Device: /dev/block/mmcblk0p42
>    Display_Name: Boot
>    Storage_Name: boot
>    Backup_Path: /boot
>    Backup_Name: boot
>    Backup_Display_Name: Boot
>    Storage_Path: /boot
>    Current_File_System: emmc
>    Fstab_File_System: emmc
>    Backup_Method: dd
> 
> /cache | /dev/block/mmcblk0p46 | Size: 377MB Used: 6MB Free: 371MB Backup Size: 6MB
>    Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_During_Factory_Reset Wipe_Available_in_GUI IsPresent 
>    Primary_Block_Device: /dev/block/mmcblk0p46
>    Display_Name: Cache
>    Storage_Name: Cache
>    Backup_Path: /cache
>    Backup_Name: cache
>    Backup_Display_Name: Cache
>    Storage_Path: /cache
>    Current_File_System: ext4
>    Fstab_File_System: ext4
>    Backup_Method: files
> 
> /system | /dev/block/mmcblk0p45 | Size: 2645MB Used: 1063MB Free: 1581MB Backup Size: 1063MB
>    Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_Available_in_GUI IsPresent Mount_Read_Only 
>    Primary_Block_Device: /dev/block/mmcblk0p45
>    Display_Name: System
>    Storage_Name: System
>    Backup_Path: /system
>    Backup_Name: system
>    Backup_Display_Name: System
>    Storage_Path: /system
>    Current_File_System: ext4
>    Fstab_File_System: ext4
>    Backup_Method: files
> 
> /data | /dev/block/mmcblk0p47 | Size: 0MB
>    Flags: Can_Be_Wiped Can_Be_Backed_Up Wipe_During_Factory_Reset Wipe_Available_in_GUI IsPresent Can_Be_Encrypted Is_Encrypted Has_Data_Media Can_Encrypt_Backup Use_Userdata_Encryption Is_Storage Is_Settings_Storage 
>    Symlink_Path: /data/media
>    Symlink_Mount_Point: /sdcard
>    Primary_Block_Device: /dev/block/mmcblk0p47
>    Crypto_Key_Location: /dev/block/platform/msm_sdcc.1/by-name/extra
>    Display_Name: data
>    Storage_Name: Internal Storage
>    Backup_Path: /data
>    Backup_Name: data
>    Backup_Display_Name: Data
>    Storage_Path: /data/media
>    Current_File_System: emmc
>    Fstab_File_System: ext4
>    Backup_Method: dd
>    MTP_Storage_ID: 65539
> 
> /misc | /dev/block/mmcblk0p24 | Size: 1MB
>    Flags: IsPresent 
>    Primary_Block_Device: /dev/block/mmcblk0p24
>    Display_Name: misc
>    Storage_Name: misc
>    Backup_Path: /misc
>    Backup_Name: misc
>    Backup_Display_Name: misc
>    Storage_Path: /misc
>    Current_File_System: emmc
>    Fstab_File_System: emmc
>    Backup_Method: dd
> 
> /recovery | /dev/block/mmcblk0p43 | Size: 24MB
>    Flags: Can_Be_Backed_Up IsPresent Can_Flash_Img 
>    Primary_Block_Device: /dev/block/mmcblk0p43
>    Display_Name: Recovery
>    Storage_Name: recovery
>    Backup_Path: /recovery
>    Backup_Name: recovery
>    Backup_Display_Name: Recovery
>    Storage_Path: /recovery
>    Current_File_System: emmc
>    Fstab_File_System: emmc
>    Backup_Method: dd
> 
> /devlog | /dev/block/mmcblk0p39 | Size: 29MB Used: 26MB Free: 3MB Backup Size: 26MB
>    Flags: Can_Be_Mounted Can_Be_Wiped IsPresent 
>    Primary_Block_Device: /dev/block/mmcblk0p39
>    Display_Name: devlog
>    Storage_Name: devlog
>    Backup_Path: /devlog
>    Backup_Name: devlog
>    Backup_Display_Name: devlog
>    Storage_Path: /devlog
>    Current_File_System: ext4
>    Fstab_File_System: ext4
>    Backup_Method: files
> 
> /carrier | /dev/block/mmcblk0p37 | Size: 24MB Used: 4MB Free: 20MB Backup Size: 4MB
>    Flags: Can_Be_Mounted Can_Be_Wiped IsPresent 
>    Primary_Block_Device: /dev/block/mmcblk0p37
>    Display_Name: carrier
>    Storage_Name: carrier
>    Backup_Path: /carrier
>    Backup_Name: carrier
>    Backup_Display_Name: carrier
>    Storage_Path: /carrier
>    Current_File_System: ext4
>    Fstab_File_System: ext4
>    Backup_Method: files
> 
> /reserve | /dev/block/mmcblk0p41 | Size: 45MB Used: 0MB Free: 45MB Backup Size: 0MB
>    Flags: Can_Be_Mounted Can_Be_Wiped IsPresent 
>    Primary_Block_Device: /dev/block/mmcblk0p41
>    Display_Name: reserve
>    Storage_Name: reserve
>    Backup_Path: /reserve
>    Backup_Name: reserve
>    Backup_Display_Name: reserve
>    Storage_Path: /reserve
>    Current_File_System: vfat
>    Fstab_File_System: vfat
>    Backup_Method: files
> 
> /external_sd | /dev/block/mmcblk1p1 | Size: 121917MB Used: 6043MB Free: 115873MB Backup Size: 0MB
>    Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_Available_in_GUI Removable IsPresent Has_Android_Secure Is_Storage 
>    Symlink_Path: /external_sd/.android_secure
>    Symlink_Mount_Point: /and-sec
>    Primary_Block_Device: /dev/block/mmcblk1p1
>    Alternate_Block_Device: /dev/block/mmcblk1
>    Display_Name: Micro SDcard
>    Storage_Name: Micro SDcard
>    Backup_Path: /and-sec
>    Backup_Name: and-sec
>    Backup_Display_Name: Android Secure
>    Storage_Path: /external_sd
>    Current_File_System: exfat
>    Fstab_File_System: vfat
>    Backup_Method: files
>    MTP_Storage_ID: 65537
> 
> /usb_otg |  | Size: 0MB Used: 0MB Free: 0MB Backup Size: 0MB
>    Flags: Can_Be_Mounted Can_Be_Wiped Wipe_Available_in_GUI Removable Is_Storage 
>    Primary_Block_Device: /dev/block/sda1
>    Alternate_Block_Device: /dev/block/sda
>    Display_Name: USB-OTG
>    Storage_Name: USB-OTG
>    Backup_Path: /usb_otg
>    Backup_Name: usb_otg
>    Backup_Display_Name: USB-OTG
>    Storage_Path: /usb_otg
>    Current_File_System: vfat
>    Fstab_File_System: vfat
>    Backup_Method: files
>    MTP_Storage_ID: 65538
> 
> /sd_ext | /dev/block/mmcblk1 | Size: 0MB Used: 0MB Free: 0MB Backup Size: 0MB
>    Flags: Can_Be_Mounted Can_Be_Wiped Wipe_Available_in_GUI Removable IsPresent 
>    Primary_Block_Device: /dev/block/mmcblk1p2
>    Alternate_Block_Device: /dev/block/mmcblk1
>    Display_Name: SD-Ext
>    Storage_Name: SD-Ext
>    Backup_Path: /sd_ext
>    Backup_Name: sd_ext
>    Backup_Display_Name: SD-Ext
>    Storage_Path: /sd_ext
>    Fstab_File_System: ext4
>    Backup_Method: files
> 
> I:Loading package: TWRP (/twres/ui.xml)
> I:Load XML directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/uk.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/tr.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/sv.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/sl.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/sk.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/ru.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/pt_PT.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/pt_BR.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/pl.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/nl.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/it.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/hu.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/fr.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/es.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/en.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/el.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/de.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/cz.xml' directly
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/en.xml' directly
> parsing languageFile
> parsing languageFile done
> I:PageManager::LoadFileToBuffer loading filename: '/twres/ui.xml' directly
> I:Checking resolution...
> I:Loading resources...
> I:Failed to load image from indeterminate013, error -1
> I:Loading variables...
> I:Loading mouse cursor...
> I:Loading pages...
> I:Including file: /twres/portrait.xml...
> I:PageManager::LoadFileToBuffer loading filename: '/twres/portrait.xml' directly
> I:Loading resources...
> I:Loading variables...
> I:Loading mouse cursor...
> I:Loading pages...
> I:Loading page main
> I:Loading page main2
> I:Loading page install
> I:Loading page flash_confirm
> I:Loading page flash_zip
> I:Loading page flash_done
> I:Loading page flash_sleep_and_reboot
> I:Loading page flashimage_confirm
> I:Loading page clear_vars
> I:Loading page reboot_system_routine
> I:Loading page confirm_action
> I:Loading page action_page
> I:Loading page singleaction_page
> I:Loading page action_complete
> I:Loading page filecheck
> I:Loading page rebootcheck
> I:Loading page appcheck
> I:Loading page wipe
> I:Loading page advancedwipe
> I:Loading page formatdata
> I:Loading page formatdata_confirm
> I:Loading page checkpartitionlist
> I:Loading page partitionoptions
> I:Loading page refreshfilesystem
> I:Loading page selectfilesystem
> I:Loading page backup
> I:Loading page backup_options
> I:Loading page backupname1
> I:Loading page backupname2
> I:Loading page backup_run
> I:Loading page restore
> I:Unable to open '/data/media/TWRP/BACKUPS/SH44XWM04645'
> I:Loading page restore_select
> I:Loading page renamebackup
> I:Loading page restore_run
> I:Loading page mount
> I:Loading page usb_mount
> I:Loading page usb_umount
> I:Loading page system_readonly_check
> I:Loading page reboot
> I:Loading page rebootapp
> I:Loading page system_readonly
> I:Loading page settings
> I:Loading page settings_timezone
> I:Loading page settings_screen
> I:Loading page settings_vibration
> I:Loading page settings_language
> I:Loading page copylog
> I:Loading page advanced
> I:Loading page partsdcardsel
> I:Loading page partsdcardcheck
> I:Loading page partsdcard
> I:Loading page htcdumlock
> I:Loading page repackselect
> I:Loading page repackconfirm
> I:Loading page lock
> I:Loading page filemanagerlist
> I:Loading page filemanageroptions
> I:Loading page choosedestinationfolder
> I:Loading page filemanagerrenamefile
> I:Loading page filemanagerrenamefolder
> I:Loading page filemanagerchmod
> I:Loading page filemanagerconfirm
> I:Loading page filemanageraction
> I:Loading page decrypt
> I:Loading page decrypt_pattern
> I:Loading page trydecrypt
> I:Loading page terminalcommand
> I:Loading page sideload
> I:Loading page fixcontexts
> I:Loading page slideout
> I:Loading page select_storage
> I:Loading page select_language
> I:Loading page decrypt_user
> I:Loading page cancel_decrypt
> I:Set page: 'decrypt_pattern'
> I:Switching packages (TWRP)
> Startup Commands: 
> sys.usb.ffs.ready=1
> sys.usb.config=adb
> service.adb.root=1
> ro.persistent_properties.ready=true
> ro.build.fingerprint=htc/omni_m8/m8:16.1.0/OPM8.181105.002/throwb10211651:eng/test-keys
> ro.boottime.adbd=9494169036
> ro.boottime.init=9105
> ro.boottime.init.selinux=52
> ro.boottime.init.cold_boot_wait=262
> ro.boottime.ueventd=9175605671
> ro.boottime.recovery=9457087678
> ro.boottime.chargeled=9475187733
> ro.boottime.choice_fn=9467049763
> ro.boottime.set_permissive=9444913355
> ro.boot.serialno=SH44XWM04645
> ro.serialno=SH44XWM04645
> net.bt.name=Android
> net.tethering.noprovisioning=true
> sys.usb.state=adb
> sys.usb.controller=f9200000.dwc3
> persist.sys.usb.config=adb
> persist.sys.dalvik.vm.lib.2=libart.so
> persist.sys.disable_rescue=true
> debug.atrace.tags.enableflags=0
> ro.dalvik.vm.native.bridge=0
> dalvik.vm.isa.arm.variant=krait
> dalvik.vm.isa.arm.features=default
> dalvik.vm.dexopt.secondary=true
> dalvik.vm.usejit=true
> dalvik.vm.lockprof.threshold=500
> dalvik.vm.dex2oat-Xms=64m
> dalvik.vm.dex2oat-Xmx=512m
> dalvik.vm.appimageformat=lz4
> dalvik.vm.usejitprofiles=true
> dalvik.vm.stack-trace-dir=/data/anr
> dalvik.vm.image-dex2oat-Xms=64m
> dalvik.vm.image-dex2oat-Xmx=64m
> dalvik.vm.image-dex2oat-filter=verify-at-runtime
> ro.config.ringtone=omni_ringtone1.ogg
> ro.config.alarm_alert=omni_alarm1.ogg
> ro.config.notification_sound=omni_notification1.ogg
> 0=0
> pm.dexopt.boot=extract
> pm.dexopt.ab-ota=speed-profile
> pm.dexopt.shared=speed
> pm.dexopt.install=quicken
> pm.dexopt.inactive=verify
> pm.dexopt.bg-dexopt=speed-profile
> pm.dexopt.first-boot=extract
> ro.com.google.clientidbase=android-google
> ro.com.android.dataroaming=false
> ro.com.android.wifi-watchlist=GoogleGuest
> ro.url.legal=http://www.google.com/intl/%s/mobile/android/basic/phone-legal.html
> ro.boot.dq=PASS
> ro.boot.lb=1
> ro.boot.cid=TELUS001
> ro.boot.mid=0P6B16000
> ro.boot.emmc=true
> ro.boot.mode=recovery
> ro.boot.podt=0x3E8
> ro.boot.engid=0
> ro.boot.ddrmid=(0x1)
> ro.boot.carrier=TELUS
> ro.boot.keycaps=qwerty
> ro.boot.selinux=permissive
> ro.boot.baseband=1.29.214500021.11G
> ro.boot.hardware=qcom
> ro.boot.pagesize=2048
> ro.boot.rom_type=NORMAL
> ro.boot.devicerev=5
> ro.boot.hwversion=B
> ro.boot.bootdevice=msm_sdcc.1
> ro.boot.bootloader=3.19.0.0000
> ro.boot.efuse_info=NL
> ro.boot.batt_poweron=good_battery
> ro.omni.device=m8
> ro.omni.version=8.1.0-20191021-m8-HOMEMADE
> ro.omni.fingerprint=OmniROM/8.1.0/m8/20191021.16:52
> ro.twrp.boot=1
> ro.twrp.version=3.3.1-0_CPTB-20191021-02
> ro.wifi.channels=
> ro.allow.mock.location=1
> ro.board.platform=msm8974
> ro.build.id=OPM8.181105.002
> ro.build.date=Mon Oct 21 16:51:18 EDT 2019
> ro.build.date.utc=1571691078
> ro.build.host=shadow-projects
> ro.build.tags=test-keys
> ro.build.type=eng
> ro.build.user=throwback
> ro.build.flavor=omni_m8-eng
> ro.build.display.id=omni_m8-eng 16.1.0 OPM8.181105.002 eng.throwb.20191021.165118 test-keys
> ro.build.product=m8
> ro.build.selinux=1
> ro.build.version.sdk=27
> ro.build.version.base_os=
> ro.build.version.release=16.1.0
> ro.build.version.codename=REL
> ro.build.version.incremental=eng.throwb.20191021.165118
> ro.build.version.preview_sdk=0
> ro.build.version.all_codenames=REL
> ro.build.version.security_patch=2025-12-05
> ro.build.description=omni_m8-eng 16.1.0 OPM8.181105.002 eng.throwb.20191021.165118 test-keys
> ro.build.characteristics=default
> ro.bionic.ld.warning=1
> ro.kernel.android.checkjni=1
> ro.secure=0
> ro.treble.enabled=false
> ro.vendor.product.name=omni_m8
> ro.vendor.product.brand=htc
> ro.vendor.product.model=HTC One_M8
> ro.vendor.product.device=m8
> ro.vendor.product.manufacturer=htc
> ro.zygote=zygote32
> ro.carrier=unknown
> ro.product.cpu.abi=armeabi-v7a
> ro.product.cpu.abi2=armeabi
> ro.product.cpu.abilist=armeabi-v7a,armeabi
> ro.product.cpu.abilist32=armeabi-v7a,armeabi
> ro.product.cpu.abilist64=
> ro.product.name=omni_m8
> ro.product.board=MSM8974
> ro.product.brand=htc
> ro.product.model=HTC One_M8
> ro.product.device=m8
> ro.product.locale=en-US
> ro.product.manufacturer=htc
> ro.baseband=1.29.214500021.11G
> ro.bootmode=recovery
> ro.hardware=qcom
> ro.revision=0
> ro.services.whitelist.packagelist=com.google.android.gms
> ro.bootimage.build.date=Mon Oct 21 16:51:18 EDT 2019
> ro.bootimage.build.date.utc=1571691078
> ro.bootimage.build.fingerprint=htc/omni_m8/m8:16.1.0/OPM8.181105.002/throwb10211651:eng/test-keys
> ro.bootloader=3.19.0.0000
> ro.debuggable=1
> ro.modversion=OmniROM-8.1.0-20191021-m8-HOMEMADE
> ro.setupwizard.enterprise_mode=1
> ro.property_service.version=2
> ro.control_privapp_permissions=enforce
> init.svc.adbd=running
> init.svc.ueventd=running
> init.svc.recovery=running
> init.svc.chargeled=running
> init.svc.choice_fn=stopped
> init.svc.set_permissive=stopped
> twrp.crash_counter=0
> twrp.action_complete=0
> keyguard.no_require_sim=true
> recovery=recovery
> load-modem=load-modem
> tombstoned.max_tombstone_count=50
> rmt_storage=rmt_storage
> 
> Running boot script...
> I:VendorInit:Updating device properties based on MID and CID...
> I:VendorInit:MID Found: 0P6B16000
> I:VendorInit:CID Found: TELUS001
> I:VendorInit:Current product: m8
> I:VendorInit:New product: htc_m8
> I:VendorInit:Current device: m8
> I:VendorInit:New device: htc_m8
> I:VendorInit:Current model: HTC One_M8
> I:/sbin/runatboot.sh process ended with RC=0
> Done.
> I:Is encrypted, do decrypt page first
> I:Switching packages (TWRP)
> I:Set page: 'decrypt'
> I:Set page: 'decrypt_pattern'
> I:Set page: 'trydecrypt'
> I:operation_start: 'Decrypt'
> I:PrepDecrypt:Running prepdecrypt script for TWRP...
> I:PrepDecrypt:Looking for /vendor/bin/qseecomd to update linker path...
> I:PrepDecrypt:File found! Relinking /vendor/bin/qseecomd to /sbin/qseecomd...
> I:PrepDecrypt:Looking for /vendor/bin/hw/android.hardware.keymaster@3.0-service to update linker path...
> I:PrepDecrypt:File not found. Proceeding without relinking...
> I:PrepDecrypt:Temporary system folder created at /s.
> I:PrepDecrypt:system mounted at /s.
> I:PrepDecrypt:Build.prop exists! Reading system properties from build.prop...
> I:PrepDecrypt:Current system Android SDK version: 28
> I:PrepDecrypt:No Original OS Version found. Proceeding with existing value.
> I:PrepDecrypt:Current OS version: 16.1.0
> I:PrepDecrypt:No Original security patch level found. Proceeding with existing value.
> I:PrepDecrypt:Current security patch level: 2025-12-05
> I:PrepDecrypt:Current fingerprint: htc/omni_m8/m8:16.1.0/OPM8.181105.002/throwb10211651:eng/test-keys
> I:PrepDecrypt:New fingerprint: htc/lineage_m8/m8:9/PQ3A.190801.002/c5eba4df94:userdebug/release-keys
> I:PrepDecrypt:crypto.ready=1
> I:PrepDecrypt:Script complete. Device ready for decryption.
> D:crypt_ftr->fs_size = 53215232
> I:Using scrypt with keymaster for cryptfs KDF
> I:TWRP keymaster max API: 3
> I:Signing safely-padded objectkeymaster module name is Keymaster QCOM HAL
> keymaster version is 3
> Found keymaster0 module, using keymaster0 API.
> could not open keymaster device in keystore (Operation not permitted)
> Failed to init keymaster 0/1
> E:Decrypt took too long, killing process
> I:Child process killed successfully
> Failed to decrypt data.
> I:Set page: 'decrypt'
> I:Set page: 'decrypt_pattern'
> I:operation_end - status=1
> I:Set page: 'trydecrypt'
> I:operation_start: 'Decrypt'
> D:crypt_ftr->fs_size = 53215232
> I:Using scrypt with keymaster for cryptfs KDF
> I:TWRP keymaster max API: 3
> I:Signing safely-padded objectkeymaster module name is Keymaster QCOM HAL
> keymaster version is 3
> Found keymaster0 module, using keymaster0 API.
> could not open keymaster device in keystore (Operation not permitted)
> Failed to init keymaster 0/1
> E:Decrypt took too long, killing process
> I:Child process killed successfully
> Failed to decrypt data.
> I:Set page: 'decrypt'
> I:Set page: 'decrypt_pattern'
> I:operation_end - status=1
> I:Set page: 'trydecrypt'
> I:operation_start: 'Decrypt'
> D:crypt_ftr->fs_size = 53215232
> I:Using scrypt with keymaster for cryptfs KDF
> I:TWRP keymaster max API: 3
> I:Signing safely-padded objectkeymaster module name is Keymaster QCOM HAL
> keymaster version is 3
> Found keymaster0 module, using keymaster0 API.
> could not open keymaster device in keystore (Operation not permitted)
> Failed to init keymaster 0/1
> E:Decrypt took too long, killing process
> I:Child process killed successfully
> Failed to decrypt data.
> I:Set page: 'decrypt'
> I:Set page: 'decrypt_pattern'
> I:operation_end - status=1
> I:Set page: 'cancel_decrypt'
> I:Set page: 'main'
> I:Set page: 'clear_vars'
> I:Set page: 'main2'
> I:Set page: 'main'
> I:Set page: 'clear_vars'
> I:Set page: 'main2'
> SELinux contexts loaded from /file_contexts
> Full SELinux support is present.
> I:Unable to mount settings storage during GUI startup.
> I:TWFunc::Fixup_Time: Pre-fix date and time: 2019-10-21--21-16-18
> I:TWFunc::Fixup_Time: Setting time offset from file /sys/class/rtc/rtc0/since_epoch
> I:TWFunc::Fixup_Time: Date and time corrected: 2019-10-21--21-16-18
> I:Copied file /cache/recovery/log.gz to /cache/recovery/last_log.gz
> pigz: /cache/recovery/log.gz OK, has trailing junk which was ignored
> Unable to mount /data/media/TWRP/.twrps
> I:Attempt to load settings from settings file...
> I:InfoManager file '/data/media/TWRP/.twrps' not found.
> I:Backup folder set to '/data/media/TWRP/BACKUPS/SH44XWM04645'
> I:Mount: Unable to find partition for path '/etc'
> I:Copied file /etc/recovery.fstab to /cache/recovery/recovery.fstab
> I:Version number saved to '/cache/recovery/.version'
> I:Unable to mount '/usb_otg'
> I:Actual block device: '', current file system: 'vfat'
> I:TWFunc::Set_Brightness: Setting brightness control to 255
> I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/en.xml' directly
> parsing languageFile
> parsing languageFile done
> I:Translating partition display names
> I:Backup folder set to '/data/media/TWRP/BACKUPS/SH44XWM04645'
> I:Switching packages (TWRP)
> I:Set page: 'system_readonly'
> I:Is_Mounted: Unable to find partition for path '/vendor'
> I:operation_start: 'Toggle System Mount'
> I:operation_end - status=1
> I:Set page: 'main'
> I:Set page: 'clear_vars'
> I:Set page: 'main2'
> I:Set page: 'main'
> I:Set page: 'clear_vars'
> I:Set page: 'main2'
> I:Switching packages (TWRP)
> I:Starting Adb Backup FIFO
> I:Set page: 'main'
> I:Set page: 'clear_vars'
> I:Set page: 'main2'
> I:Set page: 'advanced'
> I:Set page: 'copylog'
> I:Set page: 'action_page'
> I:operation_start: 'Copy Log'
> I:Copied file /tmp/recovery.log to /data/media/recovery.log
> I:Cannot find file /data/media/dmesg.log
> Copied kernel log to /data/media/dmesg.log
> Copied recovery log to /data/media/recovery.log.
> I:Set page: 'action_complete'
> I:operation_end - status=0

**Comment by CaptainThrowback** [comment]
Hm, not sure how this got broken. I'll have to flash LOS16 and encrypt and figure this out. I'll post back here when I have another version for you to test.

**Comment by CaptainThrowback** [comment]
This should be fixed now. Please try the below version and confirm decryption is working for you.


[twrp-3.3.1-0_CPTB-20191021-05-m8.img.zip](https://github.com/CaptainThrowback/android_device_htc_m8/files/3753193/twrp-3.3.1-0_CPTB-20191021-05-m8.img.zip)

**Comment by ghost** [comment]
This time it decrypts but then it starts to patch a system image unconditionally and powers off after finishing.

This was after I downloaded the OTA which I usually have to install manually (and was looking to find out if it worked after decrypting), but now it appears to be installed. Did you modify TWRP to install OTAs? No risk of it doing something improperly with encryption present?

**Comment by CaptainThrowback** [comment]
If you did an OTA update from system and it rebooted into TWRP automatically, prompted you to decrypt, and then installed the OTA, then you should be good. TWRP isn't supposed to have to decrypt to install the OTA zip at all, but if it does installs via the block.map method, mods that use addon.d don't get processed if they have a component on /data (like Magisk). This build includes a patch that first prompts you for your password, and then proceeds to attempt installing the OTA zip after successful decryption (or after the decryption prompt is cancelled). It sounds like it's working as expected. Thanks for your feedback!

**Comment by CaptainThrowback** [comment]
Fixed via https://github.com/CaptainThrowback/android_device_htc_m8/commit/0fc8c3a325bf97edf542417467f9a98015b88eb8

**Comment by ghost** [comment]
Two OTA updates later everything seems to work. Decryption works.

**Comment by CaptainThrowback** [comment]
I am a bit curious as to how you were able to get an OTA to install. I just tried it with the latest release and it doesn't work at all.

**Comment by ghost** [comment]
I was surprised and I thought it was your doing. Prior to encrypting I had to do install updates manually in TWRP but I was using the latest official TWRP version. To test if encryption worked I reinstalled LOS16 with addonSU but no gapps and your TWRP, and OTAs just started to install automatically.

**Comment by CaptainThrowback** [comment]
Can you try it with the latest release and see if the OTA still installs?

https://github.com/CaptainThrowback/android_device_htc_m8/releases

I was using that TWRP and yesterday's LOS 16 nightly, and when I tried to install an OTA (twice), when it rebooted into TWRP and I input my pattern, it decrypted and just went to the TWRP Home page. It didn't even try to attempt an install. So I'm wondering what's different between our devices. Mine is SuperCID but I don't think that should affect whether an OTA installs.

**Comment by ghost** [comment]
I will have to try that tomorrow.

Now that I think about it, I had my old LOS16 system with gapps originally installed (I had moved on to another daily driver) which I booted to first and it worked, then after installing the first zip you posted here through fastboot I booted back into LOS16 and started the OTA proess, it rebooted me into your TWRP and after failing to decrypt I clicked cancel and that was when it started to automatically patch stuff, it bricked the LOS16 that was on there - after I input the correct pattern at LOS16 boot screen it would try something for a minute and then just boot into TWRP.

So after installing your second zip I did a fresh LOS16 that was deliberately out of date by a day, encrypted it, and then did an OTA which your TWRP automatically installed after I input the pattern at the TWRP screen.

If I click cancel again it will probably brick my LOS16?

**Comment by CaptainThrowback** [comment]
Yes, if you have GApps installed along with the ROM and choose to cancel the decryption, and the OTA proceeds to install, the device will end up being soft bricked. That's an issue with GApps, I believe, because it needs access to something in the /data partition (apparently) for the GApps to reinstall properly. If you don't have GApps installed, the OTA should install fine even if you don't decrypt (though if you have Magisk installed for root rather than the LOS addon-su, it will be lost).

**Comment by CaptainThrowback** [comment]
So I did several tests with this. The latest version that I posted won't install the OTA because LOS places the command in the OEM section of /misc, which is where the OS version is stored. My latest TWRP ignores that portion of /misc to preserve the OEM info.

Without that patch, when data is unencrypted, the block.map fails to get created, and TWRP is unable to install the OTA. However with data encrypted, TWRP will now prompt to decrypt, and upon successful decryption or cancellation of the decrypt prompt, the OTA successfully installs. So it only works when the device is encrypted, and without the latest patch to prevent overwriting of the OEM data in /misc (this seems like something that needs to be fixed by the LOS team).

The Lineage OTA installer needs to respect the BOOTLOADER_MESSAGE_OFFSET when writing the block.map commands, so that the OEM data doesn't get overwritten every time an OTA needs to be installed, and so that the newer TWRP will be looking in the correct place for the OTA install commands. Maybe this is something that @bgcngm can look into as well.

**Comment by bgcngm** [comment]
@CaptainThrowback thanks for the heads-up. I totally forgot to pick https://github.com/LineageOS/android_device_htc_msm8974-common/commit/3f65fecb14d279c7b22c91ee59d4377b1b55cbc0 to the newer branches. Gonna merge them into lineage-16.0 and lineage-17.0 branches. Next lineage-16.0 nightly build should be good.

**Comment by ghost** [comment]
What are the consequences of having the OEM data get overwritten and how do you fix it?

**Comment by CaptainThrowback** [comment]
The only immediate affect is having your main-version (OS in bootloader) appear blank, so you won't easily know what firmware is installed on your device. You can fix it by flashing a firmware zip via fastboot or SD card method in bootloader to update the OS version again. But if you're using the official TWRP or an unofficial older than the one I built today, then it'll get wiped out again if you boot into TWRP. Or, if you install a Lineage 16 OTA from a build that doesn't include the fix mentioned above (which will be all of them to this point).

**Comment by bgcngm** [comment]
@LamaRaz can you confirm that the issue is now solved in the latest OTAs? If so, please also close this.

**Comment by CaptainThrowback** [comment]
@bgcngm @LamaRaz 

I just tested this myself, having the version with your patch included, and installing the next OTA through the LineageOS Updater, and it booted to my TWRP, installed the update without issue, and booted back to system. I checked bootloader and OS version is still present. Thanks for your help in getting this updated!
